### ISSUE TITLE
"com_travelpayouts_marker" is not initialized in your resources

### ISSUE THREAD

**Issue by Spotcloudit** [travelpayouts/travel-app-android#103]
I HAVE SET THE SDK CORRECTLY IN THE STRINGS.XML FILE BUT I HAVE THIS ERROR

` <string name="com_travelpayouts_marker" tools:ignore="167435"></string>`
` <string name="com_travelpayouts_api_token" `tools:ignore="1fc1b456ae0d7e446f7af9bdab7e84ce"></string>`

beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.travelpayouts.travel.app, PID: 5505
    java.lang.RuntimeException: Unable to create application com.travelpayouts.travel.app.App: java.lang.RuntimeException: **"com_travelpayouts_marker" is not initialized in your resources**
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: "com_travelpayouts_marker" is not initialized in your resources
        at com.travelpayouts.travel.sdk.TravelApp.requireString(TravelApp.kt:358)
        at com.travelpayouts.travel.sdk.TravelApp.access$requireString(TravelApp.kt:64)
        at com.travelpayouts.travel.sdk.TravelApp$referrer$2.invoke(TravelApp.kt:72)
        at com.travelpayouts.travel.sdk.TravelApp$referrer$2.invoke(TravelApp.kt:64)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.travelpayouts.travel.sdk.TravelApp.getReferrer(Unknown Source:2)
        at com.travelpayouts.travel.sdk.TravelApp.initAviasalesDependencies(TravelApp.kt:155)
        at com.travelpayouts.travel.sdk.TravelApp.initDependencies(TravelApp.kt:117)
        at com.travelpayouts.travel.sdk.TravelApp.onCreate(TravelApp.kt:90)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by tpsupport** [comment]
Hello,

The marker and token must be pasted between the symbols ><
```
<string name="com_travelpayouts_marker" tools:ignore="MissingTranslation">**put marker here**</string>
<string name="com_travelpayouts_api_token" tools:ignore="MissingTranslation">**put api token here**</string>
```

**Comment by Spotcloudit** [comment]
oh im idiot, thanks
