### ISSUE TITLE
Приложение падает при выборе страны в поиске

### ISSUE THREAD

**Issue by dtachkov** [travelpayouts/travel-app-android#137]
1 Запускаем приложение на Андроид 12
2. Переходим в поиск пункта назначения
3. Вводим текстом Турция и выбираем страну - Турция 
4. Приложение падает
5. E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.turkey.tickets, PID: 19152
    android.view.InflateException: Binary XML file line #12 in ru.turkey.tickets:layout/select_country_fragment: Binary XML file line #12 in ru.turkey.tickets:layout/select_country_fragment: Error inflating class aviasales.library.travelsdk.searchform.ui.EmptyView
    Caused by: android.view.InflateException: Binary XML file line #12 in ru.turkey.tickets:layout/select_country_fragment: Error inflating class aviasales.library.travelsdk.searchform.ui.EmptyView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at aviasales.library.travelsdk.searchform.feature.countryselector.view.CountrySelectorFragment.onCreateView(CountrySelectorFragment.kt:66)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassCastException: aviasales.common.ui.button.AviasalesButton cannot be cast to android.widget.Button
        at aviasales.library.travelsdk.searchform.ui.EmptyView.setupViews(EmptyView.java:69)
        at aviasales.library.travelsdk.searchform.ui.EmptyView.<init>(EmptyView.java:56)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:858) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538) 
        at aviasales.library.travelsdk.searchform.feature.countryselector.view.CountrySelectorFragment.onCreateView(CountrySelectorFragment.kt:66) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by tpsupport** [comment]
Добрый день! Спасибо, что сообщили о проблеме. Наши разработчики уже изучают проблему. Мы сообщим вам, как только она будет исправлена.

**Comment by tpsupport** [comment]
Добрый день! Разработчики исправили проблему. Проверьте, пожалуйста, если что-то пойдёт не так — сообщите нам, будем разбираться.
