### ISSUE TITLE
A problem occurred configuring root project 'travel-app-android-2.0.1

### ISSUE THREAD

**Issue by Sever-1974** [travelpayouts/travel-app-android#140]
Здравствуйте, не могу понять что от меня хотят. При первом запуске проекта выдал вот такую ошибку :+1: 

`A problem occurred configuring root project 'travel-app-android-2.0.1'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:7.4.1.
     Required by:
         project :
      > No matching variant of com.android.tools.build:gradle:7.4.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.4.1' but:
          - Variant 'apiElements' capability com.android.tools.build:gradle:7.4.1 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4.1')
          - Variant 'javadocElements' capability com.android.tools.build:gradle:7.4.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4.1')
          - Variant 'runtimeElements' capability com.android.tools.build:gradle:7.4.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4.1')
          - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.1 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4.1')`
У меня установлен JDK 11

**Comment by tpsupport** [comment]
Здравствуйте! Проверьте, указана ли у вас системная переменная «JAVA_HOME». Также проблема может быть связана с тем, что Gradle не видит библиотеку JDK 11. Перепроверьте это на своей стороне.

**Comment by Sever-1974** [comment]
Проверил, переменная JAVA_HOME установлена правильно и Java работает. Из командной строки выдаёт правильные ответы на запросы "echo %JAVA_HOME%" и "java --version"! 
А как проверить видит ли Gradle библиотеку JDK 11?

**Comment by Sever-1974** [comment]
Разобрался. Android Studio старая была.
Теперь другой вопрос : Android Studio просит поднять устаревший gradle 7.4.1 до версии 7.4.2?
И в пробной сборке Firebase начал ругаться!
Фатальное исключение: java.lang.NoClassDefFoundError
Ошибка <clinit> для класса com.facebook.imagepipeline.memory.NativeMemoryChunk; см. исключение в другой теме
Fatal Exception: java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.imagepipeline.memory.NativeMemoryChunk; see exception in other thread
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:31)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:16)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:256)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:55)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:108)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:25)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:98)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:75)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:191)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
