### ISSUE TITLE
Crash on some devices java.lang.UnsatisfiedLinkError at SoLoader.java:405 

### ISSUE THREAD

**Issue by Jasper7** [travelpayouts/travel-app-android#142]
I see this crash for some devices:

```
java.lang.UnsatisfiedLinkError at SoLoader.java:405
com.facebook.soloader.SoLoader$1.load
```

Crashes occur after a new version is uploaded, when google starts testing the application on its test devices (probably x86 arch) I see a lot of crashes in Crashlitycs and AppMetrica.

Details:
```
java.lang.NoClassDefFoundError: com.facebook.imagepipeline.memory.NativeMemoryChunk
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:31)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:16)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:256)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:55)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:108)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:25)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:98)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:75)
	at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:191)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/com.flightsbooking.tickets.app/lib-3/libimagepipeline.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:918)
	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
	at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:33)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.flightsbooking.tickets.app/lib-3/libimagepipeline.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)
	at java.lang.Runtime.load0(Runtime.java:942)
	at java.lang.System.load(System.java:1628)
	at com.facebook.soloader.SoLoader$1.load(SoLoader.java:405)
	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
	at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:477)
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:860)
	... 20 more
```

I find solution for this problem here:
https://github.com/facebook/fresco/issues/2381#issuecomment-516825599

Your developers can fix this?

**Comment by tpsupport** [comment]
Hello!

Our developers fixed is issue: https://github.com/travelpayouts/travel-app-android/releases/tag/2.0.3. 

Sorry for the inconvenience caused.
