### ISSUE TITLE
Crashes on launch (SearchFormNavigation.kt:55)

### ISSUE THREAD

**Issue by Nalorokk** [travelpayouts/travel-app-android#50]
`   Process: awesome.example, PID: 28226
    java.lang.RuntimeException: Unable to start activity ComponentInfo{awesome.example/ru.aviasales.ui.activity.MainActivity}: java.lang.IllegalStateException: Required value was null.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Required value was null.
        at com.jetradar.navigation.SearchFormNavigation.bottomSheetView(SearchFormNavigation.kt:55)
        at com.jetradar.navigation.SearchFormNavigation.restoreSnapshots(SearchFormNavigation.kt:51)
        at com.jetradar.navigation.Navigator.restoreSnapshots(Navigator.kt:41)
        at com.jetradar.navigation.AppRouter.restoreState(AppRouter.kt:206)
        at ru.aviasales.ui.activity.MainActivity.onCreate(MainActivity.kt:190)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)`

**Comment by tenetko** [comment]
Hi,
Please, could you send us a bit more details on what you are trying to do?

**Comment by sarpanha-009** [comment]
Can I add my Home Page into that template ?

**Comment by TMDroid** [comment]
I'm also having this issue. I included the gradle sdk into my existing application and I'm trying to start the `ru.aviasales.ui.activity.MainActivity` activity via an intent this way

```
try {
            String packageName = "my-package-name";
            PackageInfo info = getPackageManager().getPackageInfo(packageName, PackageManager.GET_ACTIVITIES);

            for (ActivityInfo activityInfo : info.activities) {
                Log.d("ACTIVITY", activityInfo.packageName);
                Log.d("ACTIVITY", activityInfo.name);

                if (activityInfo.name.contains("ru.aviasales.ui.activity.MainActivity")) {
                    ComponentName name = new ComponentName(activityInfo.applicationInfo.packageName, activityInfo.name);

                    Intent i = new Intent(Intent.ACTION_MAIN);

                    i.addCategory(Intent.CATEGORY_LAUNCHER);
                    i.setComponent(name);

                    startActivity(i);
                }
            }

        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }
```
