### ISSUE TITLE
Pre release Travel App Android  1.3.1 The app keeps stopping

### ISSUE THREAD

**Issue by paradisthomass** [travelpayouts/travel-app-android#83]
When I click on the ticket list, the app keeps stopping.

Travel App Android  1.3.1
Test on Android 10 and 11

**Comment by ggalstian** [comment]
I have same problem!

**Comment by tpsupport** [comment]
Hello! We will release a new version of Travel App in the beginning of the next week, on Monday.

**Comment by Sveshlex** [comment]
It also has a color change issue!

**Comment by tpsupport** [comment]
@Sveshlex @ggalstian @paradisthomass new release with fixes is ready: https://github.com/travelpayouts/travel-app-android/releases/tag/1.3.8

**Comment by paradisthomass** [comment]
The issue still persists ,The app keeps stopping.

Travel App Android 1.3.8
Test on Android 10 and 11

**Comment by tpsupport** [comment]
@paradisthomass Could you please send us the track trace of the error? 
The screenshots or video where we could see the edits made in the code would be highly appreciated.

**Comment by Sveshlex** [comment]
I also have this problem, only when searching for tickets [https://drive.google.com/file/d/1CTRUHmCIF8lZT0n_HGjVZSo_TYGdbOv_/view?usp=sharing](url)

**Comment by paradisthomass** [comment]
@tpsupport ==> https://youtu.be/BJBTHZ36P0s

E: FATAL EXCEPTION: main
Process: com.travelpayouts.travel.app, PID: 29727
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}
at android.content.res.TypedArray.getColor(TypedArray.java:529)
at android.widget.TextView.readTextAppearance(TextView.java:3966)
at android.widget.TextView.(TextView.java:1027)
at android.widget.TextView.(TextView.java:968)
at android.widget.TextView.(TextView.java:964)
at android.widget.TextView.(TextView.java:960)
at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.buildHighlightHintView(TicketSegmentLayoverDelegate.kt:84)
at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.bind(TicketSegmentLayoverDelegate.kt:62)
at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:41)
at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:24)
at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:53)
at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:42)
at com.hannesdorfmann.adapterdelegates4.AdapterDelegatesManager.onBindViewHolder(AdapterDelegatesManager.java:299)
at com.hannesdorfmann.adapterdelegates4.AbsDelegationAdapter.onBindViewHolder(AbsDelegationAdapter.java:98)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
E: at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:811)
at android.view.View.layout(View.java:22169)
at android.view.ViewGroup.layout(ViewGroup.java:6325)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3173)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2683)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
at android.view.Choreographer.doCallbacks(Choreographer.java:854)
at android.view.Choreographer.doFrame(Choreographer.java:789)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
at android.os.Handler.handleCallback(Handler.java:914)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7560)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by tpsupport** [comment]
Hello,

The error was fixed.
If you have any questions, please write to support@travelpayouts.com
