### ISSUE TITLE
The app keeps stopping in the new release (1.3.8)

### ISSUE THREAD

**Issue by paradisthomass** [travelpayouts/travel-app-android#87]
The problem is still not resolved in the new release (Travel App Android 1.3.8), The app keeps stopping when clicking on the ticket list.

https://youtu.be/BJBTHZ36P0s

E: FATAL EXCEPTION: main
    Process: com.travelpayouts.travel.app, PID: 29727
    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}
        at android.content.res.TypedArray.getColor(TypedArray.java:529)
        at android.widget.TextView.readTextAppearance(TextView.java:3966)
        at android.widget.TextView.<init>(TextView.java:1027)
        at android.widget.TextView.<init>(TextView.java:968)
        at android.widget.TextView.<init>(TextView.java:964)
        at android.widget.TextView.<init>(TextView.java:960)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.buildHighlightHintView(TicketSegmentLayoverDelegate.kt:84)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.bind(TicketSegmentLayoverDelegate.kt:62)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:41)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:24)
        at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:53)
        at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:42)
        at com.hannesdorfmann.adapterdelegates4.AdapterDelegatesManager.onBindViewHolder(AdapterDelegatesManager.java:299)
        at com.hannesdorfmann.adapterdelegates4.AbsDelegationAdapter.onBindViewHolder(AbsDelegationAdapter.java:98)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
E:     at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:811)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3173)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2683)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
        at android.view.Choreographer.doCallbacks(Choreographer.java:854)
        at android.view.Choreographer.doFrame(Choreographer.java:789)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Sveshlex** [comment]
I also have a problem in version 1.3.8 https://drive.google.com/file/d/1CTRUHmCIF8lZT0n_HGjVZSo_TYGdbOv_/view?usp=sharing

**Comment by Sveshlex** [comment]
I also have a problem in version 1.3.8 https://drive.google.com/file/d/1Clt_bj8Di8fk_P-1C0udLt7kJJY1mQlP/view?usp=sharing

**Comment by tpsupport** [comment]
@paradisthomass @Sveshlex we've made a fix, could you please try running git pull? It should help.
https://github.com/travelpayouts/travel-app-android/commit/c70b4b48e8e87f9a4dd3c10e4eed3c9f05fdfd37

**Comment by paradisthomass** [comment]
I tried what you suggested, but the same problem remained. The app still keeps stopping.


24984-24984/com.travelpayouts.travel.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.travelpayouts.travel.app, PID: 24984
    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}
        at android.content.res.TypedArray.getColor(TypedArray.java:529)
        at android.widget.TextView.readTextAppearance(TextView.java:3966)
        at android.widget.TextView.<init>(TextView.java:1027)
        at android.widget.TextView.<init>(TextView.java:968)
        at android.widget.TextView.<init>(TextView.java:964)
        at android.widget.TextView.<init>(TextView.java:960)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.buildHighlightHintView(TicketSegmentLayoverDelegate.kt:84)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.bind(TicketSegmentLayoverDelegate.kt:62)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:41)
        at ru.aviasales.screen.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:24)
        at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:53)
        at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:42)
        at com.hannesdorfmann.adapterdelegates4.AdapterDelegatesManager.onBindViewHolder(AdapterDelegatesManager.java:299)
        at com.hannesdorfmann.adapterdelegates4.AbsDelegationAdapter.onBindViewHolder(AbsDelegationAdapter.java:98)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
24984-24984/com.travelpayouts.travel.app E/AndroidRuntime:     
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:811)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3173)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2683)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
        at android.view.Choreographer.doCallbacks(Choreographer.java:854)
        at android.view.Choreographer.doFrame(Choreographer.java:789)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
24984-24984/com.travelpayouts.travel.app I/Process: Sending signal. PID: 24984 SIG: 9

**Comment by tpsupport** [comment]
@paradisthomass thank you letting us know. Could you please send us the original code of your project?

**Comment by paradisthomass** [comment]
Same release (Travel App Android 1.3.8), I have added only the Policy link and my marker, API token params in strings.xml.

**Comment by Sveshlex** [comment]
@paradisthomass Everything is working now. Thank you

**Comment by Sveshlex** [comment]
@paradisthomass Everything is working now. Thank you

**Comment by Sveshlex** [comment]
@tpsupport Everything is working now. Thank you

**Comment by tpsupport** [comment]
@Sveshlex we're always glad to help you!

**Comment by Sveshlex** [comment]
@tpsupport Приложение стало закрывается, но только если на телефоне установлен русский язык, на английском работает.     https://drive.google.com/file/d/1E2Iaq_E0UHSawW1lQXKCttmLFq1EgPU5/view?usp=drivesdk

**Comment by tpsupport** [comment]
@paradisthomass We need to find out what is specified in the 3rd string of themes.xml in your project. Could you please send us that string?

**Comment by Sveshlex** [comment]
@tpsupport The color of the status bar is still not changing https://drive.google.com/file/d/1F-oL9RgvSd2HkB_vE-nWk92LKKJa-Cop/view?usp=sharing

**Comment by tpsupport** [comment]
@paradisthomass Hi, we have fixed the issue, feel free to use our latest release: 
https://github.com/travelpayouts/travel-app-android/releases/tag/1.3.9

**Comment by tpsupport** [comment]
@Sveshlex Hi! We see your ticket in our support, we'll contact you there as soon as the problem is resolved.

**Comment by paradisthomass** [comment]
@tpsupport    Thank you.

**Comment by paradisthomass** [comment]
@tpsupport  Bug in the latest release 1.3.9

When I click the "**Faster by**"  the first time and then the second time, and when I go back The app keeps stopping.


https://user-images.githubusercontent.com/81306421/114869284-19c8b900-9df7-11eb-9f43-6fe453328cc9.mp4



2021-04-15 13:34:45.986 13969-13969/com.travelpayouts.travel.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.travelpayouts.travel.app, PID: 13969
    kotlin.UninitializedPropertyAccessException: lateinit property ticketDependencies has not been initialized
        at ru.aviasales.screen.ticket.presentation.TicketFragment.createComponent(TicketFragment.kt:172)
        at ru.aviasales.screen.ticket.presentation.TicketFragment.onCreate(TicketFragment.kt:60)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2938)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

Travel App Android 1.3.9
Test on Android 10 and 11

**Comment by tpsupport** [comment]
Hello,

We will fix this error in the next travel-app-android SDK update.
If you have any questions, please write to support@travelpayouts.com
