### ISSUE TITLE
The app keeps stopping in the new release (1.4.1)

### ISSUE THREAD

**Issue by paradisthomass** [travelpayouts/travel-app-android#97]
The app keeps stopping when clicking on the ticket list.

Travel App Android 1.4.1
Android 10 and 11

https://user-images.githubusercontent.com/81306421/121710601-104b8c80-cada-11eb-8fee-c33e79d66679.mp4

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.travelpayouts.travel.app, PID: 17129
    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}
        at android.content.res.TypedArray.getColor(TypedArray.java:529)
        at android.widget.TextView.readTextAppearance(TextView.java:3966)
        at android.widget.TextView.<init>(TextView.java:1027)
        at android.widget.TextView.<init>(TextView.java:968)
        at android.widget.TextView.<init>(TextView.java:964)
        at android.widget.TextView.<init>(TextView.java:960)
        at aviasales.flights.search.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.buildHighlightHintView(TicketSegmentLayoverDelegate.kt:101)
        at aviasales.flights.search.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate$ViewHolder.bind(TicketSegmentLayoverDelegate.kt:70)
        at aviasales.flights.search.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:48)
        at aviasales.flights.search.ticket.presentation.adapter.delegate.TicketSegmentLayoverDelegate.onBindViewHolder(TicketSegmentLayoverDelegate.kt:31)
        at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:53)
        at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:42)
        at com.hannesdorfmann.adapterdelegates4.AdapterDelegatesManager.onBindViewHolder(AdapterDelegatesManager.java:299)
        at com.hannesdorfmann.adapterdelegates4.AbsDelegationAdapter.onBindViewHolder(AbsDelegationAdapter.java:98)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:811)
        at android.view.View.layout(View.java:22169)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3173)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2683)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
        at android.view.Choreographer.doCallbacks(Choreographer.java:854)
        at android.view.Choreographer.doFrame(Choreographer.java:789)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by tpsupport** [comment]
Hi! Thank you for reaching out to us with this issue. The build with fix is here: [https://github.com/travelpayouts/travel-app-android/tree/dev](url) 
Could you please test it and let us know if the problem occurs?

**Comment by paradisthomass** [comment]
@tpsupport The app has been tested, and now it works well without any problem.
Thank you.
